spring.datasource.url=jdbc:mysql://localhost:3306/stocksdb?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=appuser
spring.datasource.password=apppass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=always
spring.jackson.serialization.indent-output=true
spring.jackson.serialization.write-dates-as-timestamps=false
server.error.include-message=always
app.service-name=Stock Service
app.version=5.0.0
spring.main.banner-mode=off
